### ISSUE TITLE
Does not start on Linux

### ISSUE THREAD

**Issue by lluchs** [ClonkGeist/Windmill#1]
It continuously prints this error on the console:

```
 % firefox -app application.ini
There is no or not fully supported native function support available for this operating system (Linux). Use limited fallback.
Sass: Scss-File modification detected: contextMenu (global/contextMenu.scss)
Sass: trying to reload definition 'contextMenu'
Sass: trying to reload definition 'mainFrame'
Sass error: Required import scss-file not found (contextMenu)
Sass: Write file: /home/lukas/src/openclonk/Windmill/chrome/styles/main.css
```

**Comment by lluchs** [comment]
The issue is that the file `chrome/styles/scss/global/contextmenu.scss`should be named `contextMenu.scss`.

**Comment by ClonkGeist** [comment]
Fixed this now, but I still would like to mention that there is still no support for linux systems. (We didn't want everyone to wait for it)

So many things may still not work. (Especially starting processes, playerselection, ...)
